---

- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Install kubernetes python package
  ansible.builtin.pip:
    name: kubernetes

- name: Install helm if not exists
  unarchive:
    src: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: 0755
    remote_src: true
  args:
    creates: /usr/local/bin/helm

