---

- name: Create cert-manager namespace
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Download cert-manager CRDs
  ansible.builtin.get_url:
    url: https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.crds.yaml
    dest: ~/cert-manager.crds.yaml
    mode: '0664'

- name: Apply cert-manager CRD manifest to the cluster
  kubernetes.core.k8s:
    state: present
    src: ~/cert-manager.crds.yaml
    namespace: cert-manager
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Remove cert-manager CRD manifests from disk
  file:
    path: ~/cert-manager.crds.yaml
    state: absent

- name: Add jetstack chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy latest version of cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: false
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Copy cluster issuer manifest
  ansible.builtin.copy:
    src: cluster-issuer.yaml
    dest: ~/cluster-issuer.yaml

- name: Apply cluster issuer manifest to the cluster
  kubernetes.core.k8s:
    state: present
    src: ~/cluster-issuer.yaml
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Remove cluster issuer manifest from disk
  file:
    path: ~/cluster-issuer.yaml
    state: absent

- name: Create nginx namespace
  kubernetes.core.k8s:
    name: nginx
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Download NGINX manifest to the cluster
  ansible.builtin.get_url:
    url: https://gist.githubusercontent.com/nu12/7e99b2ec26df8250c894874a221e56b2/raw
    dest: ~/nginx.yaml

- name: Replace host
  ansible.builtin.replace:
    path: ~/nginx.yaml
    regexp: example.com
    replace: _PLACEHOLDER_FQND_

- name: Apply NGINX manifest to the cluster
  kubernetes.core.k8s:
    state: present
    src: ~/nginx.yaml
    namespace: nginx
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Remove NGINX manifest from disk
  file:
    path: ~/nginx.yaml
    state: absent