name: Create K3s cluster
on: [workflow_dispatch]
jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: terraform
        run: |
          sed -i -e "s/_PLACEHOLDER_SUBSCRIPTION_/${{secrets.ARM_SUBSCRIPTION_ID}}/g" -e "s/_PLACEHOLDER_STORAGE_ACCOUNT_/${{secrets.STORAGE_ACCOUNT_NAME}}/g" terraform/backend.conf

          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PUBLIC}}" > ~/.ssh/id_rsa.pub
          echo "${{secrets.SSH_PRIVATE}}" > ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa

          cat ~/.ssh/id_rsa.pub

          export ARM_CLIENT_ID="${{secrets.ARM_CLIENT_ID}}"
          export ARM_CLIENT_SECRET="${{secrets.ARM_CLIENT_SECRET}}"
          export ARM_TENANT_ID="${{secrets.ARM_TENANT_ID}}"
          export ARM_SUBSCRIPTION_ID="${{secrets.ARM_SUBSCRIPTION_ID}}"

          terraform -chdir=terraform/ init -backend-config=backend.conf
          terraform -chdir=terraform/ apply -auto-approve

      # Get terraform outputs

      - name: ansible
        run: |
          ansible-playbook ansible/site.yml -i ansible/inventory/k3s/hosts.ini
      
      # Change master-ip group_vars/all.yml
      # Change master-ip hosts.ini
      